services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main_server:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
      - trainer
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main_trainer:app --host 0.0.0.0 --port 8001'
    volumes:
      - .:/app
    expose:
      - 8001
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  evaluator:
    build:
      context: .
      dockerfile: Dockerfile.evaluator
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main_evaluator:app --host 0.0.0.0 --port 8002'
    volumes:
      - .:/app
    expose:
      - 8002
    ports:
      - 8002:8002
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
      - server
      - trainer
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data: